"""Add user_id to order table

Revision ID: 48b7018f2b6f
Revises: faf2edbf0ed9
Create Date: 2025-02-27 16:10:04.455988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b7018f2b6f'
down_revision: Union[str, None] = 'faf2edbf0ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
