"""Update ondelete for order items

Revision ID: b628ea9a891d
Revises: fd7c00ec3bdc
Create Date: 2025-03-16 11:19:19.827392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b628ea9a891d'
down_revision: Union[str, None] = 'fd7c00ec3bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
