"""Update nullable fields

Revision ID: da80cc25fb59
Revises: 48b7018f2b6f
Create Date: 2025-02-27 16:40:26.554354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da80cc25fb59'
down_revision: Union[str, None] = '48b7018f2b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'schedule_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'delivery_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'schedule_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
