"""Update nullable fields

Revision ID: e0df8476797d
Revises: da80cc25fb59
Create Date: 2025-02-27 16:42:04.949328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0df8476797d'
down_revision: Union[str, None] = 'da80cc25fb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('schedule_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('delivery_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('delivery_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('schedule_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
